package com.github.hashpot.ui.theme

import androidx.compose.ui.graphics.Color

val Purple80 = Color(0xFFD0BCFF)
val PurpleGrey80 = Color(0xFFCCC2DC)
val Pink80 = Color(0xFFEFB8C8)

val Purple40 = Color(0xFF6650a4)
val PurpleGrey40 = Color(0xFF625b71)
val Pink40 = Color(0xFF7D5260)

val primaryLightHighContrast = Color(0xFF352B00)
val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
val primaryContainerLightHighContrast = Color(0xFF574800)
val onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
val secondaryLightHighContrast = Color(0xFF352B00)
val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
val secondaryContainerLightHighContrast = Color(0xFF574803)
val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
val tertiaryLightHighContrast = Color(0xFF253000)
val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightHighContrast = Color(0xFF3E4F00)
val onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
val errorLightHighContrast = Color(0xFF600004)
val onErrorLightHighContrast = Color(0xFFFFFFFF)
val errorContainerLightHighContrast = Color(0xFF98000A)
val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
val backgroundLightHighContrast = Color(0xFFFFF9EF)
val onBackgroundLightHighContrast = Color(0xFF1F1B10)
val surfaceLightHighContrast = Color(0xFFFFF9EF)
val onSurfaceLightHighContrast = Color(0xFF000000)
val surfaceVariantLightHighContrast = Color(0xFFECE2C5)
val onSurfaceVariantLightHighContrast = Color(0xFF000000)
val outlineLightHighContrast = Color(0xFF312C19)
val outlineVariantLightHighContrast = Color(0xFF4F4934)
val scrimLightHighContrast = Color(0xFF000000)
val inverseSurfaceLightHighContrast = Color(0xFF343024)
val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
val inversePrimaryLightHighContrast = Color(0xFFE9C400)
val surfaceDimLightHighContrast = Color(0xFFBFB8A7)
val surfaceBrightLightHighContrast = Color(0xFFFFF9EF)
val surfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightHighContrast = Color(0xFFF9F0DD)
val surfaceContainerLightHighContrast = Color(0xFFEAE2CF)
val surfaceContainerHighLightHighContrast = Color(0xFFDCD4C2)
val surfaceContainerHighestLightHighContrast = Color(0xFFCDC6B4)


val primaryDarkHighContrast = Color(0xFFFFF6DF)
val onPrimaryDarkHighContrast = Color(0xFF000000)
val primaryContainerDarkHighContrast = Color(0xFFFFD700)
val onPrimaryContainerDarkHighContrast = Color(0xFF2C2300)
val secondaryDarkHighContrast = Color(0xFFFFEFBE)
val onSecondaryDarkHighContrast = Color(0xFF000000)
val secondaryContainerDarkHighContrast = Color(0xFFD7C274)
val onSecondaryContainerDarkHighContrast = Color(0xFF0F0B00)
val tertiaryDarkHighContrast = Color(0xFFEBFFAD)
val onTertiaryDarkHighContrast = Color(0xFF000000)
val tertiaryContainerDarkHighContrast = Color(0xFFC2E84F)
val onTertiaryContainerDarkHighContrast = Color(0xFF1D2700)
val errorDarkHighContrast = Color(0xFFFFECE9)
val onErrorDarkHighContrast = Color(0xFF000000)
val errorContainerDarkHighContrast = Color(0xFFFFAEA4)
val onErrorContainerDarkHighContrast = Color(0xFF220001)
val backgroundDarkHighContrast = Color(0xFF161308)
val onBackgroundDarkHighContrast = Color(0xFFEAE2CF)
val surfaceDarkHighContrast = Color(0xFF161308)
val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkHighContrast = Color(0xFF4D4732)
val onSurfaceVariantDarkHighContrast = Color(0xFFFFFFFF)
val outlineDarkHighContrast = Color(0xFFFAEFD2)
val outlineVariantDarkHighContrast = Color(0xFFCCC2A7)
val scrimDarkHighContrast = Color(0xFF000000)
val inverseSurfaceDarkHighContrast = Color(0xFFEAE2CF)
val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
val inversePrimaryDarkHighContrast = Color(0xFF564700)
val surfaceDimDarkHighContrast = Color(0xFF161308)
val surfaceBrightDarkHighContrast = Color(0xFF555042)
val surfaceContainerLowestDarkHighContrast = Color(0xFF000000)
val surfaceContainerLowDarkHighContrast = Color(0xFF231F14)
val surfaceContainerDarkHighContrast = Color(0xFF343024)
val surfaceContainerHighDarkHighContrast = Color(0xFF3F3B2E)
val surfaceContainerHighestDarkHighContrast = Color(0xFF4B4739)
